# Generated by Django 5.2.5 on 2025-09-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='center',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='center',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='port',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='port',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tradepartneraddress',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tradepartneraddress',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
