# Generated by Django 5.2.5 on 2025-08-23 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_userprofile_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('short_code', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('short_code', models.CharField(max_length=6, unique=True)),
                ('reporting_tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='demoapp.reportingtenant')),
            ],
        ),
    ]
