# Generated by Django 5.2.5 on 2025-08-26 11:33

import demoapp.custom_fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_currency_address_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='created',
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='address',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='address',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='created',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='created',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='updated',
        ),
        migrations.AlterField(
            model_name='address',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demoapp.tenant'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='entity',
            name='short_name',
            field=demoapp.custom_fields.UpperCharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='entity',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demoapp.tenant'),
        ),
    ]
