# Generated by Django 5.2.5 on 2025-08-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_remove_address_created_remove_address_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='places_api_json',
            field=models.JSONField(blank=True),
        ),
    ]
