# Generated by Django 5.2.5 on 2025-09-05 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_alter_address_city_alter_address_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='address_line',
        ),
        migrations.RemoveField(
            model_name='center',
            name='city',
        ),
        migrations.RemoveField(
            model_name='center',
            name='country',
        ),
        migrations.RemoveField(
            model_name='center',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='center',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='center',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='center',
            name='state',
        ),
        migrations.AddField(
            model_name='center',
            name='center_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='center_address', to='demoapp.address'),
        ),
    ]
