# Generated by Django 5.2.5 on 2025-08-26 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0006_alter_address_places_api_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='places_api_json',
        ),
    ]
