# Generated by Django 5.2.5 on 2025-08-29 10:03

import demoapp.model_helpers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0008_center_centerparticular_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='center',
            name='external_ids',
        ),
        migrations.RemoveField(
            model_name='center',
            name='factory_license_date',
        ),
        migrations.RemoveField(
            model_name='center',
            name='tally_mapping_name',
        ),
        migrations.RemoveField(
            model_name='entityuseraccess',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='entityuseraccess',
            name='permissions',
        ),
        migrations.AddField(
            model_name='center',
            name='licence_issuer',
            field=models.CharField(default='State Registration', max_length=60),
        ),
        migrations.AlterField(
            model_name='center',
            name='factory_license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demoapp.tenant'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demoapp.tenant'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='tenant',
            field=models.ForeignKey(limit_choices_to=demoapp.model_helpers.limit_to_active, on_delete=django.db.models.deletion.PROTECT, to='demoapp.tenant'),
        ),
        migrations.DeleteModel(
            name='CenterParticular',
        ),
    ]
