# Generated by Django 5.2.5 on 2025-08-29 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0009_remove_center_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='center',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
