# Generated by Django 5.2.5 on 2025-08-29 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0011_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='demoapp.center'),
        ),
    ]
