# Generated by Django 5.2.5 on 2025-08-30 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0014_tax_alter_warehouse_name_alter_warehouse_short_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='demoapp.tenant'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demoapp.tenant'),
        ),
    ]
