# Generated by Django 5.2.5 on 2025-08-30 06:59

import demoapp.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0015_alter_entity_tenant_alter_item_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='code',
            field=demoapp.custom_fields.UpperCharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
