# Generated by Django 5.2.5 on 2025-08-30 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0017_tradepartnercategory_tradepartner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradepartner',
            name='pan_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradepartner',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tradepartner',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='demoapp.entity'),
        ),
        migrations.AlterField(
            model_name='tradepartner',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demoapp.tenant'),
        ),
    ]
