# Generated by Django 5.2.5 on 2025-08-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0018_tradepartner_pan_date_tradepartner_pan_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradepartner',
            name='mobile_no',
        ),
    ]
