# Generated by Django 5.2.5 on 2025-08-30 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0019_remove_tradepartner_mobile_no'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tradepartner',
            unique_together=set(),
        ),
    ]
