# Generated by Django 5.2.5 on 2025-08-30 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0020_alter_tradepartner_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tradepartner',
            unique_together={('short_name', 'tenant')},
        ),
    ]
