# Generated by Django 5.2.5 on 2025-08-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0021_alter_tradepartner_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradepartner',
            name='pan_date',
        ),
        migrations.RemoveField(
            model_name='tradepartner',
            name='pan_number',
        ),
    ]
