# Generated by Django 5.2.5 on 2025-09-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0023_port_vehicleweight_adjustmentreason_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dispatchlineitem',
            name='dispatch_bale_partial_unique_25may2025',
        ),
    ]
