# Generated by Django 5.2.5 on 2025-09-01 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0024_remove_dispatchlineitem_dispatch_bale_partial_unique_25may2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='dispatch_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='demoapp.dispatchorder'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='demoapp.driver'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='demoapp.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demoapp.tenant'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='trade_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demoapp.tradepartner'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='demoapp.vehicle'),
        ),
    ]
