# Generated by Django 5.2.5 on 2025-09-01 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0025_alter_goodsreceiptnote_dispatch_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='transaction_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demoapp.currency'),
        ),
    ]
