# Generated by Django 5.2.5 on 2025-09-02 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0026_alter_goodsreceiptnote_transaction_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchorder',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demoapp.tenant'),
        ),
        migrations.AlterField(
            model_name='dispatchorder',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demoapp.warehouse'),
        ),
        migrations.AlterField(
            model_name='grnlineitem',
            name='documents',
            field=models.ManyToManyField(blank=True, null=True, to='demoapp.document'),
        ),
    ]
