# Generated by Django 5.2.5 on 2025-09-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0027_alter_dispatchorder_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='locale',
            field=models.CharField(choices=[('en-IN', 'India - English (en-IN)')], default='en-IN', max_length=32),
        ),
    ]
