# Generated by Django 5.2.5 on 2025-09-02 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0028_alter_userprofile_locale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='designation',
        ),
    ]
