# Generated by Django 5.2.5 on 2025-09-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0031_alter_userprofile_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnlineitem',
            name='documents',
            field=models.ManyToManyField(blank=True, to='demoapp.document'),
        ),
    ]
