# Generated by Django 5.2.5 on 2025-09-03 13:00

import demoapp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0033_userprofile_email_otp_userprofile_email_otp_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_otp',
            field=models.PositiveIntegerField(blank=True, default=demoapp.models.random_pin, null=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)]),
        ),
    ]
